services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dating
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: 1237894560
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dating
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1237894560
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: